FROM python:3

RUN apt-get update -y && apt-get install --no-install-recommends -y -q ca-certificates python3-dev python3-setuptools python3-pip

RUN python3 -m pip install jupyter papermill nteract-scrapbook