name: tb16
channels:
  - conda-forge
dependencies:
  - ipykernel==5.3.0
  - pip
  - GDAL==3.1.0
  - pip: 
    - rasterio==1.1.5
    - nteract-scrapbook==0.4.1
    - papermill==2.1.2
    - folium==0.9.1
    - shapely==1.7.0
    - matplotlib==3.2.1
    - scikit-image==0.17.2