version: '3.1'
services:
  nb1request:
    build: 
      context: ./nb1_request
    environment:
      - SCIHUB_UN=$SCIHUB_UN
      - SCIHUB_PW=$SCIHUB_PW
  nb2classify:
    build: 
      context: ./nb2_download_classify/docker
    environment:
      - SCIHUB_UN=$SCIHUB_UN
      - SCIHUB_PW=$SCIHUB_PW
  nb3aggregate:
    build: ./nb3_aggregate/docker/